# DOCKER_BUILDKIT=1 docker build -t dev/project_base:latest -f Dockerfile.dev ..
FROM python:3.12-bullseye
RUN apt-get update
RUN apt-get install sqlite3

RUN curl -sSL https://install.python-poetry.org/ | python -
RUN echo 'alias poetry="/root/.local/bin/poetry"' >> ~/.bashrc

WORKDIR '/home/project_base/'

