repos:
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.1
    hooks:
        # Run the linter.
        - id: ruff
          args: [ --fix ]
        # Run the formatter.
        - id: ruff-format
-   repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
    -   id: flake8
        args: ["--config", ".flake8"]
-   repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
    -   id: bandit
        args: ["--ini", ".bandit", "-r", "sources/backend"]
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.6.1
    hooks:
    -   id: mypy
        args: ["--config-file", "mypy.ini"]