#!/bin/bash

# Run pre-commit in Docker before pushing
docker run --rm -v "./sources:/app/sources" -v "./tests:/app/tests" -t pre-commit-runner

# Capture the exit code of the Docker run command
if [ $? -ne 0 ]; then
    echo "Pre-commit checks failed. Push aborted."
    exit 1
fi
