name: Security

on: [push, pull_request]

jobs:
  bandit:
    runs-on: ubuntu-latest
    name: Bandit
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install bandit
        run: pip install bandit>=1.7.10
      - name: Run bandit
        run: bandit --ini .bandit -r sources/backend